# Generated by Django 4.2.6 on 2023-10-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('systems', '0001_initial'),
        ('agents', '0001_initial'),
        ('factions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='headquarters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint'),
        ),
        migrations.AddField(
            model_name='agent',
            name='starting_faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.faction'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
