# Generated by Django 4.2.6 on 2023-10-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_alter_waypoint_orbits'),
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='headquarters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_headquarters', to='systems.waypoint'),
        ),
    ]
