# Generated by Django 4.2.6 on 2023-10-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0003_remove_faction_systems_delete_factionsystemlink'),
        ('agents', '0003_alter_agent_headquarters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='starting_faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factions.faction'),
        ),
    ]
