# Generated by Django 4.2.6 on 2023-10-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_user_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='symbol',
            new_name='agent',
        ),
    ]
