# Generated by Django 4.2.6 on 2023-11-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('symbol', models.CharField(choices=[('COSMIC', 'Cosmic'), ('VOID', 'Void'), ('GALACTIC', 'Galactic'), ('QUANTUM', 'Quantum'), ('DOMINION', 'Dominion'), ('ASTRO', 'Astro'), ('CORSAIRS', 'Corsairs'), ('OBSIDIAN', 'Obsidian'), ('AEGIS', 'Aegis'), ('UNITED', 'United'), ('SOLITARY', 'Solitary'), ('COBALT', 'Cobalt'), ('OMEGA', 'Omega'), ('ECHO', 'Echo'), ('LORDS', 'Lords'), ('CULT', 'Cult'), ('ANCIENTS', 'Ancients'), ('SHADOW', 'Shadow'), ('ETHEREAL', 'Ethereal')], max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('is_recruiting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FactionTrait',
            fields=[
                ('symbol', models.CharField(choices=[('BUREAUCRATIC', 'Bureaucratic'), ('SECRETIVE', 'Secretive'), ('CAPITALISTIC', 'Capitalistic'), ('INDUSTRIOUS', 'Industrious'), ('PEACEFUL', 'Peaceful'), ('DISTRUSTFUL', 'Distrustful'), ('WELCOMING', 'Welcoming'), ('SMUGGLERS', 'Smugglers'), ('SCAVENGERS', 'Scavengers'), ('REBELLIOUS', 'Rebellious'), ('EXILES', 'Exiles'), ('PIRATES', 'Pirates'), ('RAIDERS', 'Raiders'), ('CLAN', 'Clan'), ('GUILD', 'Guild'), ('DOMINION', 'Dominion'), ('FRINGE', 'Fringe'), ('FORSAKEN', 'Forsaken'), ('ISOLATED', 'Isolated'), ('LOCALIZED', 'Localized'), ('ESTABLISHED', 'Established'), ('NOTABLE', 'Notable'), ('DOMINANT', 'Dominant'), ('INESCAPABLE', 'Inescapable'), ('INNOVATIVE', 'Innovative'), ('BOLD', 'Bold'), ('VISIONARY', 'Visionary'), ('CURIOUS', 'Curious'), ('DARING', 'Daring'), ('EXPLORATORY', 'Exploratory'), ('RESOURCEFUL', 'Resourceful'), ('FLEXIBLE', 'Flexible'), ('COOPERATIVE', 'Cooperative'), ('UNITED', 'United'), ('STRATEGIC', 'Strategic'), ('INTELLIGENT', 'Intelligent'), ('RESEARCH_FOCUSED', 'Research_Focused'), ('COLLABORATIVE', 'Collaborative'), ('PROGRESSIVE', 'Progressive'), ('MILITARISTIC', 'Militaristic'), ('TECHNOLOGICALLY_ADVANCED', 'Technologically Advanced'), ('AGGRESSIVE', 'Aggressive'), ('IMPERIALISTIC', 'Imperialistic'), ('TREASURE_HUNTERS', 'Treasure_Hunters'), ('DEXTEROUS', 'Dexterous'), ('UNPREDICTABLE', 'Unpredictable'), ('BRUTAL', 'Brutal'), ('FLEETING', 'Fleeting'), ('ADAPTABLE', 'Adaptable'), ('SELF_SUFFICIENT', 'Self Sufficient'), ('DEFENSIVE', 'Defensive'), ('PROUD', 'Proud'), ('DIVERSE', 'Diverse'), ('INDEPENDENT', 'Independent'), ('SELF_INTERESTED', 'Self Interested'), ('FRAGMENTED', 'Fragmented'), ('COMMERCIAL', 'Commercial'), ('FREE_MARKETS', 'Free Markets'), ('ENTREPRENEURIAL', 'Entrepreneurial')], max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='FactionTraitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.faction')),
                ('faction_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.factiontrait')),
            ],
        ),
    ]
