# Generated by Django 4.2.6 on 2023-11-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factions', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='headquarters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faction_headquarters', to='systems.system'),
        ),
        migrations.AddField(
            model_name='faction',
            name='traits',
            field=models.ManyToManyField(related_name='factions', through='factions.FactionTraitLink', to='factions.factiontrait'),
        ),
    ]
