# Generated by Django 4.2.6 on 2023-10-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_alter_tradegood_symbol'),
        ('factions', '0003_remove_faction_systems_delete_factionsystemlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='headquarters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faction_headquarters', to='systems.system'),
        ),
    ]
