# Generated by Django 4.2.6 on 2023-10-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('PROCUREMENT', 'Procurement'), ('TRANSPORT', 'Transport'), ('SHUTTLE', 'Shuttle')], max_length=500)),
                ('accepted', models.BooleanField(default=False)),
                ('fulfilled', models.BooleanField(default=False)),
                ('expiration', models.DateTimeField()),
                ('deadline_to_accept', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_required', models.IntegerField()),
                ('units_fulfilled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('payment_on_accepted', models.IntegerField()),
                ('payment_on_fulfilled', models.IntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
    ]
