# Generated by Django 4.2.6 on 2023-11-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('systems', '0001_initial'),
        ('agents', '0002_initial'),
        ('factions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='trade_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.tradegood'),
        ),
        migrations.AddField(
            model_name='contract',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='contract',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.faction'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='contracts.terms'),
        ),
    ]
