# Generated by Django 4.2.6 on 2023-11-02 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('systems', '0001_initial'),
        ('factions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='trade_good_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.tradegood'),
        ),
        migrations.AddField(
            model_name='contract',
            name='faction_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.faction'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.terms'),
        ),
    ]
