# Generated by Django 4.2.6 on 2023-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='expiration',
        ),
        migrations.AlterField(
            model_name='contract',
            name='deadline_to_accept',
            field=models.DateTimeField(blank=True, null=True, verbose_name='the time at which the contract is no longer available to be accepted.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='units_fulfilled',
            field=models.IntegerField(verbose_name='the number of units fulfilled on this contract.'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='units_required',
            field=models.IntegerField(verbose_name='the number of units that need to be delivered on this contract.'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='payment_on_accepted',
            field=models.IntegerField(verbose_name='the amount of credits received up front for accepting the contract.'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='payment_on_fulfilled',
            field=models.IntegerField(verbose_name='the amount of credits received when the contract is fulfilled.'),
        ),
    ]
