# Generated by Django 4.2.6 on 2023-11-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agent',
            field=models.ForeignKey(default='jam', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='agents.agent'),
            preserve_default=False,
        ),
    ]
