# Generated by Django 4.2.6 on 2023-11-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_delivery_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='trade_good_symbol',
            new_name='trade_good',
        ),
    ]
