# Generated by Django 4.2.6 on 2023-11-04 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='the total duration of the cooldown in seconds.')),
                ('remaining_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='the remaining duration of the cooldown in seconds')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='the date and time when the cooldown expires in ISO 8601 format.')),
            ],
        ),
    ]
