# Generated by Django 4.2.6 on 2023-10-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('fleet', '0001_initial'),
        ('systems', '0001_initial'),
        ('factions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipyard',
            name='waypoint_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint'),
        ),
        migrations.AddField(
            model_name='shipregistration',
            name='faction_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.faction'),
        ),
        migrations.AddField(
            model_name='shipnavroute',
            name='departure_waypoint_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_departure', to='systems.waypoint', verbose_name='Depreciated, use origin'),
        ),
        migrations.AddField(
            model_name='shipnavroute',
            name='destination_waypoint_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_destination', to='systems.waypoint'),
        ),
        migrations.AddField(
            model_name='shipnavroute',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_origin', to='systems.waypoint'),
        ),
        migrations.AddField(
            model_name='shipnav',
            name='current_system_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AddField(
            model_name='shipnav',
            name='current_waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint'),
        ),
        migrations.AddField(
            model_name='shipnav',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.shipnavroute'),
        ),
        migrations.AddField(
            model_name='shipmountlink',
            name='mount',
            field=models.ForeignKey(choices=[('MOUNT_GAS_SIPHON_I', 'Mount Gas Siphon I'), ('MOUNT_GAS_SIPHON_II', 'Mount Gas Siphon II'), ('MOUNT_GAS_SIPHON_III', 'Mount Gas Siphon III'), ('MOUNT_SURVEYOR_I', 'Mount Surveyor I'), ('MOUNT_SURVEYOR_II', 'Mount Surveyor II'), ('MOUNT_SURVEYOR_III', 'Mount Surveyor III'), ('MOUNT_SENSOR_ARRAY_I', 'Mount Sensor Array I'), ('MOUNT_SENSOR_ARRAY_II', 'Mount Sensor Array II'), ('MOUNT_SENSOR_ARRAY_III', 'Mount Sensor Array III'), ('MOUNT_MINING_LASER_I', 'Mount Mining Laser I'), ('MOUNT_MINING_LASER_II', 'Mount Mining Laser II'), ('MOUNT_MINING_LASER_III', 'Mount Mining Laser III'), ('MOUNT_LASER_CANNON_I', 'Mount Laser Cannon I'), ('MOUNT_MISSILE_LAUNCHER_I', 'Mount Missile Launcher I'), ('MOUNT_TURRET_I', 'Mount Turret I')], on_delete=django.db.models.deletion.CASCADE, to='fleet.mount'),
        ),
        migrations.AddField(
            model_name='shipmountlink',
            name='ship_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.ship'),
        ),
        migrations.AddField(
            model_name='shipmodulelink',
            name='module',
            field=models.ForeignKey(choices=[('MODULE_MINERAL_PROCESSOR_I', 'Module Mineral Processor I'), ('MODULE_CARGO_HOLD_I', 'Module Cargo Hold I'), ('MODULE_CREW_QUARTERS_I', 'Module Crew Quarters I'), ('MODULE_ENVOY_QUARTERS_I', 'Module Envoy Quarters I'), ('MODULE_PASSENGER_CABIN_I', 'Module Passenger Cabin I'), ('MODULE_MICRO_REFINERY_I', 'Module Micro Refinery I'), ('MODULE_ORE_REFINERY_I', 'Module Ore Refinery I'), ('MODULE_FUEL_REFINERY_I', 'Module Fuel Refinery I'), ('MODULE_SCIENCE_LAB_I', 'Module Science Lab I'), ('MODULE_JUMP_DRIVE_I', 'Module Jump Drive I'), ('MODULE_JUMP_DRIVE_II', 'Module Jump Drive II'), ('MODULE_JUMP_DRIVE_III', 'Module Jump Drive III'), ('MODULE_WARP_DRIVE_I', 'Module Warp Drive I'), ('MODULE_WARP_DRIVE_II', 'Module Warp Drive II'), ('MODULE_WARP_DRIVE_III', 'Module Warp Drive III'), ('MODULE_SHIELD_GENERATOR_I', 'Module Shield Generator I'), ('MODULE_SHIELD_GENERATOR_II', 'Module Shield Generator II')], on_delete=django.db.models.deletion.CASCADE, to='fleet.module'),
        ),
        migrations.AddField(
            model_name='shipmodulelink',
            name='ship_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.ship'),
        ),
        migrations.AddField(
            model_name='shipcomponent',
            name='requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.installationrequirements'),
        ),
        migrations.AddField(
            model_name='shipcargoinventory',
            name='ship_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.ship'),
        ),
        migrations.AddField(
            model_name='shipcargoinventory',
            name='trade_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.tradegood'),
        ),
        migrations.AddField(
            model_name='ship',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='ship',
            name='cooldown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.cooldown'),
        ),
        migrations.AddField(
            model_name='ship',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.shipcrew'),
        ),
        migrations.AddField(
            model_name='ship',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.engine'),
        ),
        migrations.AddField(
            model_name='ship',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.frame'),
        ),
        migrations.AddField(
            model_name='ship',
            name='modules',
            field=models.ManyToManyField(related_name='ships', through='fleet.ShipModuleLink', to='fleet.module'),
        ),
        migrations.AddField(
            model_name='ship',
            name='mounts',
            field=models.ManyToManyField(related_name='ships', through='fleet.ShipMountLink', to='fleet.mount'),
        ),
        migrations.AddField(
            model_name='ship',
            name='nav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.shipnav'),
        ),
        migrations.AddField(
            model_name='ship',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.reactor'),
        ),
        migrations.AddField(
            model_name='ship',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.shipregistration'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='symbol',
            field=models.ForeignKey(choices=[('REACTOR_SOLAR_I', 'Reactor Solar I'), ('REACTOR_FUSION_I', 'Reactor Fusion I'), ('REACTOR_FISSION_I', 'Reactor Fission I'), ('REACTOR_CHEMICAL_I', 'Reactor Chemical I'), ('REACTOR_ANTIMATTER_I', 'Reactor Antimatter I')], on_delete=django.db.models.deletion.CASCADE, related_name='reactors', to='fleet.shipcomponent'),
        ),
        migrations.AddField(
            model_name='mountdepositlink',
            name='mount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.mount'),
        ),
        migrations.AddField(
            model_name='mountdepositlink',
            name='trade_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.tradegood'),
        ),
        migrations.AddField(
            model_name='mount',
            name='deposits',
            field=models.ManyToManyField(related_name='mounts', through='fleet.MountDepositLink', to='systems.tradegood'),
        ),
        migrations.AddField(
            model_name='mount',
            name='symbol',
            field=models.ForeignKey(choices=[('MOUNT_GAS_SIPHON_I', 'Mount Gas Siphon I'), ('MOUNT_GAS_SIPHON_II', 'Mount Gas Siphon II'), ('MOUNT_GAS_SIPHON_III', 'Mount Gas Siphon III'), ('MOUNT_SURVEYOR_I', 'Mount Surveyor I'), ('MOUNT_SURVEYOR_II', 'Mount Surveyor II'), ('MOUNT_SURVEYOR_III', 'Mount Surveyor III'), ('MOUNT_SENSOR_ARRAY_I', 'Mount Sensor Array I'), ('MOUNT_SENSOR_ARRAY_II', 'Mount Sensor Array II'), ('MOUNT_SENSOR_ARRAY_III', 'Mount Sensor Array III'), ('MOUNT_MINING_LASER_I', 'Mount Mining Laser I'), ('MOUNT_MINING_LASER_II', 'Mount Mining Laser II'), ('MOUNT_MINING_LASER_III', 'Mount Mining Laser III'), ('MOUNT_LASER_CANNON_I', 'Mount Laser Cannon I'), ('MOUNT_MISSILE_LAUNCHER_I', 'Mount Missile Launcher I'), ('MOUNT_TURRET_I', 'Mount Turret I')], on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to='fleet.shipcomponent'),
        ),
        migrations.AddField(
            model_name='module',
            name='symbol',
            field=models.ForeignKey(choices=[('MODULE_MINERAL_PROCESSOR_I', 'Module Mineral Processor I'), ('MODULE_CARGO_HOLD_I', 'Module Cargo Hold I'), ('MODULE_CREW_QUARTERS_I', 'Module Crew Quarters I'), ('MODULE_ENVOY_QUARTERS_I', 'Module Envoy Quarters I'), ('MODULE_PASSENGER_CABIN_I', 'Module Passenger Cabin I'), ('MODULE_MICRO_REFINERY_I', 'Module Micro Refinery I'), ('MODULE_ORE_REFINERY_I', 'Module Ore Refinery I'), ('MODULE_FUEL_REFINERY_I', 'Module Fuel Refinery I'), ('MODULE_SCIENCE_LAB_I', 'Module Science Lab I'), ('MODULE_JUMP_DRIVE_I', 'Module Jump Drive I'), ('MODULE_JUMP_DRIVE_II', 'Module Jump Drive II'), ('MODULE_JUMP_DRIVE_III', 'Module Jump Drive III'), ('MODULE_WARP_DRIVE_I', 'Module Warp Drive I'), ('MODULE_WARP_DRIVE_II', 'Module Warp Drive II'), ('MODULE_WARP_DRIVE_III', 'Module Warp Drive III'), ('MODULE_SHIELD_GENERATOR_I', 'Module Shield Generator I'), ('MODULE_SHIELD_GENERATOR_II', 'Module Shield Generator II')], on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='fleet.shipcomponent'),
        ),
        migrations.AddField(
            model_name='fuelconsumedlog',
            name='ship_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.ship'),
        ),
        migrations.AddField(
            model_name='frame',
            name='symbol',
            field=models.ForeignKey(choices=[('FRAME_PROBE', 'Frame Probe'), ('FRAME_DRONE', 'Frame Drone'), ('FRAME_INTERCEPTOR', 'Frame Interceptor'), ('FRAME_RACER', 'Frame Racer'), ('FRAME_FIGHTER', 'Frame Fighter'), ('FRAME_FRIGATE', 'Frame Frigate'), ('FRAME_SHUTTLE', 'Frame Shuttle'), ('FRAME_EXPLORER', 'Frame Explorer'), ('FRAME_MINER', 'Frame Miner'), ('FRAME_LIGHT_FREIGHTER', 'Frame Light Freighter'), ('FRAME_HEAVY_FREIGHTER', 'Frame Heavy Freighter'), ('FRAME_TRANSPORT', 'Frame Transport'), ('FRAME_DESTROYER', 'Frame Destroyer'), ('FRAME_CRUISER', 'Frame Cruiser'), ('FRAME_CARRIER', 'Frame Carrier')], on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='fleet.shipcomponent'),
        ),
        migrations.AddField(
            model_name='engine',
            name='symbol',
            field=models.ForeignKey(choices=[('ENGINE_IMPULSE_DRIVE_I', 'Engine Impulse Drive I'), ('ENGINE_ION_DRIVE_I', 'Engine Ion Drive I'), ('ENGINE_ION_DRIVE_II', 'Engine Ion Drive II'), ('ENGINE_HYPER_DRIVE_I', 'Engine Hyper Drive I')], on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='fleet.shipcomponent'),
        ),
    ]
