# Generated by Django 4.2.6 on 2023-11-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipregistration',
            old_name='faction_symbol',
            new_name='faction',
        ),
    ]
