# Generated by Django 4.2.6 on 2023-11-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_rename_faction_symbol_shipregistration_faction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='fuelCapacity',
            new_name='fuel_capacity',
        ),
        migrations.RenameField(
            model_name='shipnav',
            old_name='current_system_symbol',
            new_name='current_system',
        ),
    ]
