# Generated by Django 4.2.6 on 2023-10-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='symbol',
            field=models.ForeignKey(choices=[('MODULE_MINERAL_PROCESSOR_I', 'Module Mineral Processor I'), ('MODULE_CARGO_HOLD_I', 'Module Cargo Hold I'), ('MODULE_CREW_QUARTERS_I', 'Module Crew Quarters I'), ('MODULE_ENVOY_QUARTERS_I', 'Module Envoy Quarters I'), ('MODULE_PASSENGER_CABIN_I', 'Module Passenger Cabin I'), ('MODULE_MICRO_REFINERY_I', 'Module Micro Refinery I'), ('MODULE_ORE_REFINERY_I', 'Module Ore Refinery I'), ('MODULE_FUEL_REFINERY_I', 'Module Fuel Refinery I'), ('MODULE_SCIENCE_LAB_I', 'Module Science Lab I'), ('MODULE_WARP_DRIVE_I', 'Module Warp Drive I'), ('MODULE_WARP_DRIVE_II', 'Module Warp Drive II'), ('MODULE_WARP_DRIVE_III', 'Module Warp Drive III'), ('MODULE_SHIELD_GENERATOR_I', 'Module Shield Generator I'), ('MODULE_SHIELD_GENERATOR_II', 'Module Shield Generator II')], on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='fleet.shipcomponent'),
        ),
        migrations.AlterField(
            model_name='shipcomponent',
            name='symbol',
            field=models.CharField(choices=[('FRAME_PROBE', 'Frame Probe'), ('FRAME_DRONE', 'Frame Drone'), ('FRAME_INTERCEPTOR', 'Frame Interceptor'), ('FRAME_RACER', 'Frame Racer'), ('FRAME_FIGHTER', 'Frame Fighter'), ('FRAME_FRIGATE', 'Frame Frigate'), ('FRAME_SHUTTLE', 'Frame Shuttle'), ('FRAME_EXPLORER', 'Frame Explorer'), ('FRAME_MINER', 'Frame Miner'), ('FRAME_LIGHT_FREIGHTER', 'Frame Light Freighter'), ('FRAME_HEAVY_FREIGHTER', 'Frame Heavy Freighter'), ('FRAME_TRANSPORT', 'Frame Transport'), ('FRAME_DESTROYER', 'Frame Destroyer'), ('FRAME_CRUISER', 'Frame Cruiser'), ('FRAME_CARRIER', 'Frame Carrier'), ('REACTOR_SOLAR_I', 'Reactor Solar I'), ('REACTOR_FUSION_I', 'Reactor Fusion I'), ('REACTOR_FISSION_I', 'Reactor Fission I'), ('REACTOR_CHEMICAL_I', 'Reactor Chemical I'), ('REACTOR_ANTIMATTER_I', 'Reactor Antimatter I'), ('ENGINE_IMPULSE_DRIVE_I', 'Engine Impulse Drive I'), ('ENGINE_ION_DRIVE_I', 'Engine Ion Drive I'), ('ENGINE_ION_DRIVE_II', 'Engine Ion Drive II'), ('ENGINE_HYPER_DRIVE_I', 'Engine Hyper Drive I'), ('MODULE_MINERAL_PROCESSOR_I', 'Module Mineral Processor I'), ('MODULE_CARGO_HOLD_I', 'Module Cargo Hold I'), ('MODULE_CREW_QUARTERS_I', 'Module Crew Quarters I'), ('MODULE_ENVOY_QUARTERS_I', 'Module Envoy Quarters I'), ('MODULE_PASSENGER_CABIN_I', 'Module Passenger Cabin I'), ('MODULE_MICRO_REFINERY_I', 'Module Micro Refinery I'), ('MODULE_ORE_REFINERY_I', 'Module Ore Refinery I'), ('MODULE_FUEL_REFINERY_I', 'Module Fuel Refinery I'), ('MODULE_SCIENCE_LAB_I', 'Module Science Lab I'), ('MODULE_WARP_DRIVE_I', 'Module Warp Drive I'), ('MODULE_WARP_DRIVE_II', 'Module Warp Drive II'), ('MODULE_WARP_DRIVE_III', 'Module Warp Drive III'), ('MODULE_SHIELD_GENERATOR_I', 'Module Shield Generator I'), ('MODULE_SHIELD_GENERATOR_II', 'Module Shield Generator II'), ('MOUNT_GAS_SIPHON_I', 'Mount Gas Siphon I'), ('MOUNT_GAS_SIPHON_II', 'Mount Gas Siphon II'), ('MOUNT_GAS_SIPHON_III', 'Mount Gas Siphon III'), ('MOUNT_SURVEYOR_I', 'Mount Surveyor I'), ('MOUNT_SURVEYOR_II', 'Mount Surveyor II'), ('MOUNT_SURVEYOR_III', 'Mount Surveyor III'), ('MOUNT_SENSOR_ARRAY_I', 'Mount Sensor Array I'), ('MOUNT_SENSOR_ARRAY_II', 'Mount Sensor Array II'), ('MOUNT_SENSOR_ARRAY_III', 'Mount Sensor Array III'), ('MOUNT_MINING_LASER_I', 'Mount Mining Laser I'), ('MOUNT_MINING_LASER_II', 'Mount Mining Laser II'), ('MOUNT_MINING_LASER_III', 'Mount Mining Laser III'), ('MOUNT_LASER_CANNON_I', 'Mount Laser Cannon I'), ('MOUNT_MISSILE_LAUNCHER_I', 'Mount Missile Launcher I'), ('MOUNT_TURRET_I', 'Mount Turret I')], max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipmodulelink',
            name='module',
            field=models.ForeignKey(choices=[('MODULE_MINERAL_PROCESSOR_I', 'Module Mineral Processor I'), ('MODULE_CARGO_HOLD_I', 'Module Cargo Hold I'), ('MODULE_CREW_QUARTERS_I', 'Module Crew Quarters I'), ('MODULE_ENVOY_QUARTERS_I', 'Module Envoy Quarters I'), ('MODULE_PASSENGER_CABIN_I', 'Module Passenger Cabin I'), ('MODULE_MICRO_REFINERY_I', 'Module Micro Refinery I'), ('MODULE_ORE_REFINERY_I', 'Module Ore Refinery I'), ('MODULE_FUEL_REFINERY_I', 'Module Fuel Refinery I'), ('MODULE_SCIENCE_LAB_I', 'Module Science Lab I'), ('MODULE_WARP_DRIVE_I', 'Module Warp Drive I'), ('MODULE_WARP_DRIVE_II', 'Module Warp Drive II'), ('MODULE_WARP_DRIVE_III', 'Module Warp Drive III'), ('MODULE_SHIELD_GENERATOR_I', 'Module Shield Generator I'), ('MODULE_SHIELD_GENERATOR_II', 'Module Shield Generator II')], on_delete=django.db.models.deletion.CASCADE, to='fleet.module'),
        ),
        migrations.AlterField(
            model_name='shipyardshipmodulelink',
            name='module',
            field=models.ForeignKey(choices=[('MODULE_MINERAL_PROCESSOR_I', 'Module Mineral Processor I'), ('MODULE_CARGO_HOLD_I', 'Module Cargo Hold I'), ('MODULE_CREW_QUARTERS_I', 'Module Crew Quarters I'), ('MODULE_ENVOY_QUARTERS_I', 'Module Envoy Quarters I'), ('MODULE_PASSENGER_CABIN_I', 'Module Passenger Cabin I'), ('MODULE_MICRO_REFINERY_I', 'Module Micro Refinery I'), ('MODULE_ORE_REFINERY_I', 'Module Ore Refinery I'), ('MODULE_FUEL_REFINERY_I', 'Module Fuel Refinery I'), ('MODULE_SCIENCE_LAB_I', 'Module Science Lab I'), ('MODULE_WARP_DRIVE_I', 'Module Warp Drive I'), ('MODULE_WARP_DRIVE_II', 'Module Warp Drive II'), ('MODULE_WARP_DRIVE_III', 'Module Warp Drive III'), ('MODULE_SHIELD_GENERATOR_I', 'Module Shield Generator I'), ('MODULE_SHIELD_GENERATOR_II', 'Module Shield Generator II')], on_delete=django.db.models.deletion.CASCADE, to='fleet.module'),
        ),
    ]
