# Generated by Django 4.2.6 on 2023-11-09 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_frame_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='condition',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='condition',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.'),
        ),
    ]
