# Generated by Django 4.2.6 on 2023-11-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_engine_condition_alter_reactor_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipyardship',
            name='crew',
        ),
        migrations.AddField(
            model_name='shipyardship',
            name='crew_capacity',
            field=models.IntegerField(default=1, verbose_name='the maximum number of crew members the ship can support.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipyardship',
            name='crew_required',
            field=models.IntegerField(default=1, verbose_name='the minimum number of crew members required to maintain the ship.'),
            preserve_default=False,
        ),
    ]
