# Generated by Django 4.2.6 on 2023-10-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_module_symbol_alter_shipcomponent_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipyardship',
            name='ship_type',
            field=models.CharField(choices=[('SHIP_PROBE', 'Ship Probe'), ('SHIP_MINING_DRONE', 'Ship Mining Drone'), ('SHIP_SIPHON_DRONE', 'Ship Siphon Drone'), ('SHIP_INTERCEPTOR', 'Ship Interceptor'), ('SHIP_LIGHT_HAULER', 'Ship Light Hauler'), ('SHIP_COMMAND_FRIGATE', 'Ship Command Frigate'), ('SHIP_EXPLORER', 'Ship Explorer'), ('SHIP_HEAVY_FREIGHTER', 'Ship Heavy Freighter'), ('SHIP_LIGHT_SHUTTLE', 'Ship Light Shuttle'), ('SHIP_ORE_HOUND', 'Ship Ore Hound'), ('SHIP_REFINING_FREIGHTER', 'Ship Refining Freighter'), ('SHIP_SURVEYOR', 'Ship Surveyor')], max_length=500),
        ),
    ]
