# Generated by Django 4.2.6 on 2023-11-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_rename_fuelcapacity_frame_fuel_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='crew',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of crew required for operation.'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of power required from the reactor.'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='the number of module slots required for installation.'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='crew',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of crew required for operation.'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of power required from the reactor.'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='the number of module slots required for installation.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='crew',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of crew required for operation.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of power required from the reactor.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='the number of module slots required for installation.'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='crew',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of crew required for operation.'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of power required from the reactor.'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='the number of module slots required for installation.'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='crew',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of crew required for operation.'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='the amount of power required from the reactor.'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='the number of module slots required for installation.'),
        ),
    ]
