# Generated by Django 4.2.6 on 2023-10-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_jumpgatelink_remove_jumpgatesystemlink_jump_gate_and_more'),
        ('agents', '0008_rename_symbol_user_agent'),
        ('fleet', '0005_alter_shipyardship_ship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipcomponent',
            name='requirements',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='mountingPoints',
            new_name='mounting_points',
        ),
        migrations.RenameField(
            model_name='shipmodulelink',
            old_name='ship_symbol',
            new_name='ship',
        ),
        migrations.RenameField(
            model_name='shipmountlink',
            old_name='ship_symbol',
            new_name='ship',
        ),
        migrations.RenameField(
            model_name='shipnavroute',
            old_name='destination_waypoint_symbol',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='shipyard',
            old_name='waypoint_symbol',
            new_name='waypoint',
        ),
        migrations.RenameField(
            model_name='shipyardtransaction',
            old_name='shipyard_waypoint_symbol',
            new_name='shipyard',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='id',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='mount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mount',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='cooldown',
        ),
        migrations.RemoveField(
            model_name='shipnav',
            name='current_waypoint',
        ),
        migrations.RemoveField(
            model_name='shipnavroute',
            name='departure_waypoint_symbol',
        ),
        migrations.RemoveField(
            model_name='shipyardship',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='cooldown',
            name='ship_symbol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fleet.ship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='crew',
            field=models.IntegerField(default=None, verbose_name='the amount of crew required for operation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='power',
            field=models.IntegerField(default=None, verbose_name='the amount of power required from the reactor.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='slots',
            field=models.IntegerField(default=None, verbose_name='the number of module slots required for installation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='tradegood_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.tradegood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='crew',
            field=models.IntegerField(default=None, verbose_name='the amount of crew required for operation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='power',
            field=models.IntegerField(default=None, verbose_name='the amount of power required from the reactor.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='slots',
            field=models.IntegerField(default=None, verbose_name='the number of module slots required for installation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='tradegood_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.tradegood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='crew',
            field=models.IntegerField(default=None, verbose_name='the amount of crew required for operation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='power',
            field=models.IntegerField(default=None, verbose_name='the amount of power required from the reactor.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='slots',
            field=models.IntegerField(default=None, verbose_name='the number of module slots required for installation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='tradegood_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.tradegood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mount',
            name='crew',
            field=models.IntegerField(default=None, verbose_name='the amount of crew required for operation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mount',
            name='power',
            field=models.IntegerField(default=None, verbose_name='the amount of power required from the reactor.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mount',
            name='slots',
            field=models.IntegerField(default=None, verbose_name='the number of module slots required for installation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mount',
            name='tradegood_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.tradegood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactor',
            name='crew',
            field=models.IntegerField(default=None, verbose_name='the amount of crew required for operation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactor',
            name='power',
            field=models.IntegerField(default=None, verbose_name='the amount of power required from the reactor.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactor',
            name='slots',
            field=models.IntegerField(default=None, verbose_name='the number of module slots required for installation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactor',
            name='tradegood_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.tradegood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipnav',
            name='waypoint',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint', verbose_name="The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipyardshiplink',
            name='activity',
            field=models.CharField(choices=[('WEAK', 'Weak'), ('GROWING', 'Growing'), ('STRONG', 'Strong')], default=None, max_length=500, verbose_name='the activity level of a trade good. If the good is an import, this represents how strong consumption is for the good. If the good is an export, this represents how strong the production is for the good.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipyardshiplink',
            name='purchase_price',
            field=models.IntegerField(default=None, verbose_name='the price of the ship at this shipyard.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipyardshiplink',
            name='supply',
            field=models.CharField(choices=[('SCARCE', 'Scarce'), ('LIMITED', 'Limited'), ('MODERATE', 'Moderate'), ('ABUNDANT', 'Abundant')], default=None, max_length=500, verbose_name='the supply of the ship at this shipyard.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mount',
            name='deposits',
            field=models.ManyToManyField(choices=[('QUARTZ_SAND', 'Quartz Sand'), ('SILICON_CRYSTALS', 'Silicon Crystals'), ('PRECIOUS_STONES', 'Precious Stones'), ('ICE_WATER', 'Ice Water'), ('AMMONIA_ICE', 'Ammonia Ice'), ('IRON_ORE', 'Iron Ore'), ('COPPER_ORE', 'Copper Ore'), ('SILVER_ORE', 'Silver Ore'), ('ALUMINUM_ORE', 'Aluminum Ore'), ('GOLD_ORE', 'Gold Ore'), ('PLATINUM_ORE', 'Platinum Ore'), ('DIAMONDS', 'Diamonds'), ('URANITE_ORE', 'Uranite Ore'), ('MERITIUM_ORE', 'Meritium Ore')], related_name='mounts', through='fleet.MountDepositLink', to='systems.tradegood'),
        ),
        migrations.AlterField(
            model_name='mountdepositlink',
            name='mount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits_link', to='fleet.mount'),
        ),
        migrations.AlterField(
            model_name='mountdepositlink',
            name='trade_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposited_by_link', to='systems.tradegood'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='crew',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.shipcrew'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='nav',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.shipnav'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.shipregistration'),
        ),
        migrations.AlterField(
            model_name='shipregistration',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.DeleteModel(
            name='InstallationRequirements',
        ),
        migrations.DeleteModel(
            name='ShipComponent',
        ),
    ]
