# Generated by Django 4.2.6 on 2023-11-02 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_engine_crew_alter_engine_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='strength',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="mounts that have this value, such as mining lasers, denote how powerful this mount's capabilities are."),
        ),
    ]
