# Generated by Django 4.2.6 on 2023-11-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_shipyardship_crew_shipyardship_crew_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipyardtransaction',
            name='shipyard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fleet.shipyard', verbose_name='the symbol of the waypoint where the transaction took place.'),
        ),
    ]
