# Generated by Django 4.2.6 on 2023-11-02 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_alter_mount_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='shipregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='shipregistration',
            name='ship',
            field=models.OneToOneField(default='GIMMICONTRACTS-1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration', serialize=False, to='fleet.ship'),
            preserve_default=False,
        ),
    ]
