# Generated by Django 4.2.6 on 2023-11-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_rename_ship_symbol_cooldown_ship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipcargoinventory',
            old_name='ship_symbol',
            new_name='ship',
        ),
    ]
