# Generated by Django 4.2.6 on 2023-11-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_rename_ship_symbol_shipcargoinventory_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipcargoinventory',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='fleet.ship'),
        ),
    ]
