# Generated by Django 4.2.6 on 2023-11-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_rename_ship_symbol_markettransaction_ship'),
        ('fleet', '0011_alter_shipcargoinventory_ship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('signature', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='the unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.')),
                ('expiration', models.DateTimeField()),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MODERATE', 'Moderate'), ('LARGE', 'Large')], max_length=255)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='systems.waypoint')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='fleet.survey')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='systems.tradegood')),
            ],
        ),
    ]
