# Generated by Django 4.2.6 on 2023-10-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0003_remove_faction_systems_delete_factionsystemlink'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='id',
        ),
        migrations.AlterField(
            model_name='chart',
            name='waypoint_symbol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chart', serialize=False, to='systems.waypoint', verbose_name='The chart of a system or waypoint, which makes the location visible to other agents.'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='system_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='systems.system'),
        ),
        migrations.CreateModel(
            name='SystemFactionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.faction')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.system')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='factions',
            field=models.ManyToManyField(related_name='systems', through='systems.SystemFactionLink', to='factions.faction'),
        ),
    ]
