# Generated by Django 4.2.6 on 2023-11-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumpgate',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_gate_destinations', to='systems.waypoint'),
        ),
    ]
