# Generated by Django 4.2.6 on 2023-10-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_remove_chart_id_alter_chart_waypoint_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaypointModifier',
            fields=[
                ('symbol', models.CharField(choices=[('STRIPPED', 'Stripped'), ('UNSTABLE', 'Unstable'), ('RADIATION_LEAK', 'Radiation Leak'), ('CRITICAL_LIMIT', 'Critical Limit'), ('CIVIL_UNREST', 'Civil Unrest')], max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RenameField(
            model_name='waypoint',
            old_name='faction_symbol',
            new_name='faction',
        ),
        migrations.RenameField(
            model_name='waypoint',
            old_name='system_symbol',
            new_name='system',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='is_under_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='orbits',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint', verbose_name='the symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='waypoint_type',
            field=models.CharField(choices=[('PLANET', 'Planet'), ('GAS_GIANT', 'Gas Giant'), ('MOON', 'Moon'), ('ORBITAL_STATION', 'Orbital Station'), ('JUMP_GATE', 'Jump Gate'), ('ASTEROID_FIELD', 'Asteroid Field'), ('ASTEROID', 'Asteroid'), ('ENGINEERED_ASTEROID', 'Engineered Asteroid'), ('ASTEROID_BASE', 'Asteroid Base'), ('NEBULA', 'Nebula'), ('DEBRIS_FIELD', 'Debris Field'), ('GRAVITY_WELL', 'Gravity Well'), ('ARTIFICIAL_GRAVITY_WELL', 'Artificial Gravity Well'), ('FUEL_STATION', 'Fuel Station')], max_length=500),
        ),
        migrations.CreateModel(
            name='WaypointModifierLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint')),
                ('waypoint_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.waypointmodifier')),
            ],
        ),
        migrations.AddField(
            model_name='waypoint',
            name='modifiers',
            field=models.ManyToManyField(related_name='waypoints', through='systems.WaypointModifierLink', to='systems.waypointmodifier'),
        ),
    ]
