# Generated by Django 4.2.6 on 2023-11-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_alter_jumpgate_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.IntegerField(verbose_name='the number of units of the trade good required to complete construction of the waypoint.')),
                ('fulfilled', models.IntegerField(verbose_name='the number of units of the trade good that have been delivered to the construction site.')),
                ('TradeGood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_site', to='systems.tradegood')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_site', to='systems.waypoint')),
            ],
        ),
    ]
