# Generated by Django 4.2.6 on 2023-11-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_alter_jumpgate_waypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettradegoodlink',
            name='activity',
            field=models.CharField(blank=True, choices=[('WEAK', 'Weak'), ('GROWING', 'Growing'), ('STRONG', 'Strong')], max_length=500, null=True, verbose_name='the activity level of a trade good. If the good is an import, this represents how strong consumption is for the good. If the good is an export, this represents how strong the production is for the good.'),
        ),
    ]
