# Generated by Django 4.2.6 on 2023-10-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_waypointmodifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='orbits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.waypoint', verbose_name='the symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.'),
        ),
    ]
