# Generated by Django 4.2.6 on 2023-11-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_rename_ship_symbol_shipcargoinventory_ship'),
        ('systems', '0004_alter_markettradegoodlink_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettransaction',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='systems.market'),
        ),
        migrations.AlterField(
            model_name='markettransaction',
            name='ship_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_transactions', to='fleet.ship'),
        ),
    ]
