# Generated by Django 4.2.6 on 2023-11-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_alter_markettransaction_market_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markettransaction',
            old_name='ship_symbol',
            new_name='ship',
        ),
    ]
