# Generated by Django 4.2.6 on 2023-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_jumpgatelink_remove_jumpgatesystemlink_jump_gate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradegood',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tradegood',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
